version: '3.8'

services:
  postgres:
    container_name: db_name
    image: postgres:15.1
    restart: unless-stopped
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: 12345
      POSTGRES_NAME: postgres
    # valumes:
    #   - pgdata: /var/lib/postgresql/data
    ports:
      - 5432:5432

  chat_service:
    container_name: chat_service
    build: /chat_service
    environment:
      HTTP_PORT: :3333
      DB_HOST: db_name
      DB_PORT: 5432
      DB_USER: developer
      DB_PASSWORD: 12345
      DB_NAME: postgres
      LOG_LEVEL: debug
      KAFKA_PORT: 29092
      KAFKA_HOST: kafka
    ports:
      - 3333:3333
    depends_on:
      - postgres
  
  socket_service:
    container_name: websocket_service
    build: /websocket_service
    environment:
      SOCKET_PORT: :1111
      KAFKA_PORT: 29092
      KAFKA_HOST: kafka
      KAFKA_TOPIC: kafkatopic
      PARTITION: 0
      LOG_LEVEL: debug
    ports:
      - 1111:1111
    depends_on:
      - chat_service

  api-gateway:
    container_name: api-gateway
    build: /api-gateway
    environment:
      HTTP_PORT: :8080
      CHAT_SERVICE_HOST: chat_service
      CHAT_SERVICE_PORT: 3333
      CSV_FILE_PATH: ./config/roles.csv
      AUTH_FILE_PATH: ./config/auth.conf
      SIGNINGKEY: lknkdsjkjrw4rufdsjk094u5ifjskfj4tufnk 
    ports:
      - 8080:8080
    depends_on:
      - chat_service
    
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
     - 8080:8080
    depends_on:
      - zookeeper
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment: 
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka: 
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on: 
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=EXTERNAL_SAME_HOST://:29092, INTERNAL://:9092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT, EXTERNAL_SAME_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

