// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat_service.proto

package chat_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_e881f93b317ee75c, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type ChatReq struct {
	ChatType             string   `protobuf:"bytes,1,opt,name=chat_type,json=chatType,proto3" json:"chat_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatReq) Reset()         { *m = ChatReq{} }
func (m *ChatReq) String() string { return proto.CompactTextString(m) }
func (*ChatReq) ProtoMessage()    {}
func (*ChatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e881f93b317ee75c, []int{1}
}

func (m *ChatReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatReq.Unmarshal(m, b)
}
func (m *ChatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatReq.Marshal(b, m, deterministic)
}
func (m *ChatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatReq.Merge(m, src)
}
func (m *ChatReq) XXX_Size() int {
	return xxx_messageInfo_ChatReq.Size(m)
}
func (m *ChatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChatReq proto.InternalMessageInfo

func (m *ChatReq) GetChatType() string {
	if m != nil {
		return m.ChatType
	}
	return ""
}

type ChatRes struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ChatType             string   `protobuf:"bytes,2,opt,name=chat_type,json=chatType,proto3" json:"chat_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatRes) Reset()         { *m = ChatRes{} }
func (m *ChatRes) String() string { return proto.CompactTextString(m) }
func (*ChatRes) ProtoMessage()    {}
func (*ChatRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_e881f93b317ee75c, []int{2}
}

func (m *ChatRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatRes.Unmarshal(m, b)
}
func (m *ChatRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatRes.Marshal(b, m, deterministic)
}
func (m *ChatRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatRes.Merge(m, src)
}
func (m *ChatRes) XXX_Size() int {
	return xxx_messageInfo_ChatRes.Size(m)
}
func (m *ChatRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatRes.DiscardUnknown(m)
}

var xxx_messageInfo_ChatRes proto.InternalMessageInfo

func (m *ChatRes) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ChatRes) GetChatType() string {
	if m != nil {
		return m.ChatType
	}
	return ""
}

type UserReq struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	UserName             string   `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Bio                  string   `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	Phone                string   `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Image                string   `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserReq) Reset()         { *m = UserReq{} }
func (m *UserReq) String() string { return proto.CompactTextString(m) }
func (*UserReq) ProtoMessage()    {}
func (*UserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e881f93b317ee75c, []int{3}
}

func (m *UserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserReq.Unmarshal(m, b)
}
func (m *UserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserReq.Marshal(b, m, deterministic)
}
func (m *UserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserReq.Merge(m, src)
}
func (m *UserReq) XXX_Size() int {
	return xxx_messageInfo_UserReq.Size(m)
}
func (m *UserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserReq proto.InternalMessageInfo

func (m *UserReq) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserReq) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UserReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserReq) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *UserReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserReq) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

type UserRes struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	UserName             string   `protobuf:"bytes,4,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Bio                  string   `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	Phone                string   `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Image                string   `protobuf:"bytes,7,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRes) Reset()         { *m = UserRes{} }
func (m *UserRes) String() string { return proto.CompactTextString(m) }
func (*UserRes) ProtoMessage()    {}
func (*UserRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_e881f93b317ee75c, []int{4}
}

func (m *UserRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRes.Unmarshal(m, b)
}
func (m *UserRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRes.Marshal(b, m, deterministic)
}
func (m *UserRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRes.Merge(m, src)
}
func (m *UserRes) XXX_Size() int {
	return xxx_messageInfo_UserRes.Size(m)
}
func (m *UserRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRes.DiscardUnknown(m)
}

var xxx_messageInfo_UserRes proto.InternalMessageInfo

func (m *UserRes) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserRes) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserRes) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UserRes) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserRes) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *UserRes) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserRes) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

type UserId struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserId) Reset()         { *m = UserId{} }
func (m *UserId) String() string { return proto.CompactTextString(m) }
func (*UserId) ProtoMessage()    {}
func (*UserId) Descriptor() ([]byte, []int) {
	return fileDescriptor_e881f93b317ee75c, []int{5}
}

func (m *UserId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserId.Unmarshal(m, b)
}
func (m *UserId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserId.Marshal(b, m, deterministic)
}
func (m *UserId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserId.Merge(m, src)
}
func (m *UserId) XXX_Size() int {
	return xxx_messageInfo_UserId.Size(m)
}
func (m *UserId) XXX_DiscardUnknown() {
	xxx_messageInfo_UserId.DiscardUnknown(m)
}

var xxx_messageInfo_UserId proto.InternalMessageInfo

func (m *UserId) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type PrivateChatReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChatId               int64    `protobuf:"varint,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrivateChatReq) Reset()         { *m = PrivateChatReq{} }
func (m *PrivateChatReq) String() string { return proto.CompactTextString(m) }
func (*PrivateChatReq) ProtoMessage()    {}
func (*PrivateChatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e881f93b317ee75c, []int{6}
}

func (m *PrivateChatReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivateChatReq.Unmarshal(m, b)
}
func (m *PrivateChatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivateChatReq.Marshal(b, m, deterministic)
}
func (m *PrivateChatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivateChatReq.Merge(m, src)
}
func (m *PrivateChatReq) XXX_Size() int {
	return xxx_messageInfo_PrivateChatReq.Size(m)
}
func (m *PrivateChatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivateChatReq.DiscardUnknown(m)
}

var xxx_messageInfo_PrivateChatReq proto.InternalMessageInfo

func (m *PrivateChatReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PrivateChatReq) GetChatId() int64 {
	if m != nil {
		return m.ChatId
	}
	return 0
}

type PrivateChatRes struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChatId               int64    `protobuf:"varint,3,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	CreatedAt            string   `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrivateChatRes) Reset()         { *m = PrivateChatRes{} }
func (m *PrivateChatRes) String() string { return proto.CompactTextString(m) }
func (*PrivateChatRes) ProtoMessage()    {}
func (*PrivateChatRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_e881f93b317ee75c, []int{7}
}

func (m *PrivateChatRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivateChatRes.Unmarshal(m, b)
}
func (m *PrivateChatRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivateChatRes.Marshal(b, m, deterministic)
}
func (m *PrivateChatRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivateChatRes.Merge(m, src)
}
func (m *PrivateChatRes) XXX_Size() int {
	return xxx_messageInfo_PrivateChatRes.Size(m)
}
func (m *PrivateChatRes) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivateChatRes.DiscardUnknown(m)
}

var xxx_messageInfo_PrivateChatRes proto.InternalMessageInfo

func (m *PrivateChatRes) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PrivateChatRes) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PrivateChatRes) GetChatId() int64 {
	if m != nil {
		return m.ChatId
	}
	return 0
}

func (m *PrivateChatRes) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "chat_service.Empty")
	proto.RegisterType((*ChatReq)(nil), "chat_service.ChatReq")
	proto.RegisterType((*ChatRes)(nil), "chat_service.ChatRes")
	proto.RegisterType((*UserReq)(nil), "chat_service.UserReq")
	proto.RegisterType((*UserRes)(nil), "chat_service.UserRes")
	proto.RegisterType((*UserId)(nil), "chat_service.UserId")
	proto.RegisterType((*PrivateChatReq)(nil), "chat_service.PrivateChatReq")
	proto.RegisterType((*PrivateChatRes)(nil), "chat_service.PrivateChatRes")
}

func init() {
	proto.RegisterFile("chat_service.proto", fileDescriptor_e881f93b317ee75c)
}

var fileDescriptor_e881f93b317ee75c = []byte{
	// 433 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x94, 0xcf, 0x8b, 0xda, 0x40,
	0x14, 0xc7, 0x35, 0x31, 0x89, 0x79, 0x2d, 0x52, 0xa6, 0x8a, 0xc1, 0xb6, 0xd0, 0xe6, 0x50, 0x7a,
	0xb2, 0xd0, 0x42, 0x69, 0x8f, 0x5a, 0x5a, 0xf0, 0x22, 0x4b, 0x76, 0xbd, 0xec, 0x45, 0x46, 0xe7,
	0xad, 0x0e, 0x6c, 0x7e, 0x98, 0x8c, 0x82, 0xe7, 0xfd, 0x47, 0xf6, 0x4f, 0xd8, 0x3f, 0x71, 0x99,
	0x99, 0x44, 0x12, 0x8d, 0xb9, 0x39, 0x9f, 0xef, 0xfb, 0xf1, 0x7d, 0x6f, 0xc6, 0x00, 0x59, 0x6f,
	0xa9, 0x58, 0x66, 0x98, 0x1e, 0xf8, 0x1a, 0xc7, 0x49, 0x1a, 0x8b, 0x98, 0xbc, 0x2d, 0x33, 0xdf,
	0x01, 0xeb, 0x5f, 0x98, 0x88, 0xa3, 0xff, 0x15, 0x9c, 0xbf, 0x5b, 0x2a, 0x02, 0xdc, 0x91, 0x0f,
	0xe0, 0xaa, 0x18, 0x71, 0x4c, 0xd0, 0x6b, 0x7f, 0x6e, 0x7f, 0x73, 0x83, 0xae, 0x04, 0x77, 0xc7,
	0x04, 0xfd, 0x5f, 0x45, 0x5c, 0x46, 0x7a, 0x60, 0x70, 0xa6, 0x02, 0xcc, 0xc0, 0xe0, 0xac, 0x9a,
	0x67, 0x9c, 0xe5, 0x3d, 0xb7, 0xc1, 0x59, 0x64, 0x98, 0xca, 0x06, 0x9f, 0x00, 0x1e, 0x78, 0x9a,
	0x89, 0x65, 0x44, 0xc3, 0xa2, 0x83, 0xab, 0xc8, 0x9c, 0x86, 0x28, 0xeb, 0x3c, 0xd2, 0x42, 0xcd,
	0xeb, 0x48, 0x50, 0x88, 0xfb, 0x0c, 0x53, 0x2d, 0x9a, 0x5a, 0x94, 0x40, 0x89, 0xef, 0xc0, 0x5c,
	0xf1, 0xd8, 0xeb, 0x28, 0x2c, 0x7f, 0x92, 0x3e, 0x58, 0xc9, 0x36, 0x8e, 0xd0, 0xb3, 0x14, 0xd3,
	0x07, 0x49, 0x79, 0x48, 0x37, 0xe8, 0xd9, 0x9a, 0xaa, 0x83, 0xff, 0x72, 0xb2, 0x78, 0x39, 0x5b,
	0xd5, 0xb2, 0xd1, 0x68, 0xd9, 0x6c, 0xb2, 0xdc, 0xa9, 0xb7, 0x6c, 0xd5, 0x58, 0xb6, 0x6b, 0x2d,
	0x3b, 0x65, 0xcb, 0x5f, 0xc0, 0x96, 0x8e, 0x67, 0x8c, 0x0c, 0xc1, 0x51, 0x4d, 0x4e, 0xae, 0xed,
	0xbd, 0x12, 0xfc, 0x29, 0xf4, 0x6e, 0x52, 0x7e, 0xa0, 0x02, 0x8b, 0xfb, 0xbd, 0x16, 0x2a, 0x05,
	0x75, 0x81, 0x9c, 0xa9, 0x09, 0xcd, 0xc0, 0x96, 0xc7, 0x19, 0xf3, 0x77, 0x67, 0x35, 0x2e, 0xf7,
	0x53, 0xaa, 0x69, 0x5c, 0xab, 0x69, 0x96, 0x6b, 0xca, 0x8d, 0xae, 0x53, 0xa4, 0x02, 0xd9, 0x92,
	0x8a, 0x7c, 0x2d, 0x6e, 0x4e, 0x26, 0xe2, 0xc7, 0x93, 0x09, 0x6f, 0x64, 0xb3, 0x5b, 0xfd, 0x50,
	0xc9, 0x1f, 0x70, 0x26, 0x8c, 0x49, 0x42, 0x06, 0xe3, 0xca, 0xb3, 0xce, 0xc7, 0x1a, 0xd5, 0xe2,
	0xcc, 0x6f, 0x91, 0x39, 0xf4, 0x26, 0x8c, 0x95, 0x06, 0x20, 0x1f, 0xab, 0xa1, 0xd5, 0xfd, 0x8c,
	0x9a, 0x54, 0x59, 0x4f, 0x5b, 0x91, 0x7b, 0x3f, 0xb7, 0x92, 0x3f, 0xf0, 0x51, 0x2d, 0xd6, 0xa9,
	0xdd, 0xff, 0x3c, 0xd2, 0xb9, 0xfd, 0xcb, 0xa0, 0x19, 0x6b, 0x4a, 0x85, 0x00, 0xc3, 0xf8, 0x80,
	0x0d, 0xc9, 0xef, 0xab, 0x54, 0xff, 0xb3, 0x5b, 0xe4, 0x37, 0xd8, 0x8b, 0x84, 0x51, 0x81, 0xf5,
	0x7e, 0xb3, 0xab, 0x4d, 0xa7, 0xc3, 0xfb, 0xc1, 0x06, 0x23, 0xf5, 0xe1, 0xf8, 0x5e, 0x0e, 0x59,
	0xd9, 0x8a, 0xfd, 0x7c, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x8a, 0x7a, 0x41, 0x62, 0x04, 0x00,
	0x00,
}
