// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageId struct {
	MessageId            int64    `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageId) Reset()         { *m = MessageId{} }
func (m *MessageId) String() string { return proto.CompactTextString(m) }
func (*MessageId) ProtoMessage()    {}
func (*MessageId) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *MessageId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageId.Unmarshal(m, b)
}
func (m *MessageId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageId.Marshal(b, m, deterministic)
}
func (m *MessageId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageId.Merge(m, src)
}
func (m *MessageId) XXX_Size() int {
	return xxx_messageInfo_MessageId.Size(m)
}
func (m *MessageId) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageId.DiscardUnknown(m)
}

var xxx_messageInfo_MessageId proto.InternalMessageInfo

func (m *MessageId) GetMessageId() int64 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

type MessageReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChatId               int64    `protobuf:"varint,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	MessageText          string   `protobuf:"bytes,3,opt,name=message_text,json=messageText,proto3" json:"message_text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageReq) Reset()         { *m = MessageReq{} }
func (m *MessageReq) String() string { return proto.CompactTextString(m) }
func (*MessageReq) ProtoMessage()    {}
func (*MessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *MessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageReq.Unmarshal(m, b)
}
func (m *MessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageReq.Marshal(b, m, deterministic)
}
func (m *MessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageReq.Merge(m, src)
}
func (m *MessageReq) XXX_Size() int {
	return xxx_messageInfo_MessageReq.Size(m)
}
func (m *MessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_MessageReq proto.InternalMessageInfo

func (m *MessageReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *MessageReq) GetChatId() int64 {
	if m != nil {
		return m.ChatId
	}
	return 0
}

func (m *MessageReq) GetMessageText() string {
	if m != nil {
		return m.MessageText
	}
	return ""
}

type MessageRes struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChatId               int64    `protobuf:"varint,3,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	MessageText          string   `protobuf:"bytes,4,opt,name=message_text,json=messageText,proto3" json:"message_text,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageRes) Reset()         { *m = MessageRes{} }
func (m *MessageRes) String() string { return proto.CompactTextString(m) }
func (*MessageRes) ProtoMessage()    {}
func (*MessageRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *MessageRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRes.Unmarshal(m, b)
}
func (m *MessageRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRes.Marshal(b, m, deterministic)
}
func (m *MessageRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRes.Merge(m, src)
}
func (m *MessageRes) XXX_Size() int {
	return xxx_messageInfo_MessageRes.Size(m)
}
func (m *MessageRes) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRes.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRes proto.InternalMessageInfo

func (m *MessageRes) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MessageRes) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *MessageRes) GetChatId() int64 {
	if m != nil {
		return m.ChatId
	}
	return 0
}

func (m *MessageRes) GetMessageText() string {
	if m != nil {
		return m.MessageText
	}
	return ""
}

func (m *MessageRes) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *MessageRes) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*MessageId)(nil), "message.MessageId")
	proto.RegisterType((*MessageReq)(nil), "message.MessageReq")
	proto.RegisterType((*MessageRes)(nil), "message.MessageRes")
}

func init() {
	proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd)
}

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0xb4, 0xb8,
	0x38, 0x7d, 0x21, 0x4c, 0xcf, 0x14, 0x21, 0x59, 0x2e, 0x2e, 0xa8, 0x78, 0x7c, 0x66, 0x8a, 0x04,
	0xa3, 0x02, 0xa3, 0x06, 0x73, 0x10, 0x67, 0x2e, 0x4c, 0x5a, 0x29, 0x91, 0x8b, 0x0b, 0xaa, 0x36,
	0x28, 0xb5, 0x50, 0x48, 0x9c, 0x8b, 0xbd, 0xb4, 0x38, 0xb5, 0x08, 0xa1, 0x92, 0x0d, 0xc4, 0xf5,
	0x4c, 0x01, 0x49, 0x24, 0x67, 0x24, 0x96, 0x80, 0x24, 0x98, 0x20, 0x12, 0x20, 0xae, 0x67, 0x8a,
	0x90, 0x22, 0x17, 0x0f, 0xcc, 0xf8, 0x92, 0xd4, 0x8a, 0x12, 0x09, 0x66, 0x05, 0x46, 0x0d, 0xce,
	0x20, 0x6e, 0xa8, 0x58, 0x48, 0x6a, 0x45, 0x89, 0xd2, 0x7a, 0x46, 0x24, 0x3b, 0x8a, 0x85, 0xf8,
	0xb8, 0x98, 0xe0, 0xc6, 0x33, 0x65, 0xa6, 0x20, 0xdb, 0xc9, 0x84, 0xcb, 0x4e, 0x66, 0xbc, 0x76,
	0xb2, 0x60, 0xd8, 0x09, 0xf2, 0x75, 0x72, 0x51, 0x6a, 0x62, 0x49, 0x6a, 0x4a, 0x7c, 0x62, 0x89,
	0x04, 0x2b, 0x58, 0x01, 0x27, 0x54, 0xc4, 0x11, 0x2c, 0x5d, 0x5a, 0x90, 0x02, 0x93, 0x66, 0x83,
	0x48, 0x43, 0x45, 0x1c, 0x4b, 0x8c, 0x5a, 0x18, 0xb9, 0xf8, 0xa0, 0x2e, 0x0e, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0x15, 0xb2, 0xe0, 0xe2, 0x72, 0x4c, 0x49, 0x81, 0x0a, 0x0a, 0x09, 0xeb, 0xc1,
	0x82, 0x1e, 0x11, 0x78, 0x52, 0x58, 0x04, 0x8b, 0x95, 0x18, 0x84, 0x2c, 0xb8, 0xb8, 0xdd, 0x32,
	0xf3, 0xe0, 0x5a, 0x85, 0xd0, 0x55, 0x79, 0xa6, 0xe0, 0xd0, 0xe9, 0x24, 0x14, 0x25, 0x90, 0x9e,
	0x9a, 0x07, 0x8e, 0x5c, 0x7d, 0xa8, 0x82, 0x24, 0x36, 0x30, 0xd7, 0x18, 0x10, 0x00, 0x00, 0xff,
	0xff, 0x06, 0x95, 0xb3, 0xad, 0xfc, 0x01, 0x00, 0x00,
}
